# To add a new cell, type '# %%'
# To add a new markdown cell, type '# %% [markdown]'
# %% [markdown]
# # Gathered Notebook
# Gathered from ```/Users/jeffreymew/Downloads/Pet Detector PyTorch/PetDetectorTraining.ipynb```
# 
# |   |   |
# |---|---|
# |&nbsp;&nbsp;&nbsp|This notebook was generated by the Gather Extension. The intent is that it contains only the code and cells required to produce the same results as the cell originally selected for gathering. Please note that the Python analysis is quite conservative, so if it is unsure whether a line of code is necessary for execution, it will err on the side of including it.|
# 
# **Are you satisfied with the code that was gathered?**
# 
# [Yes](https://command:python.datascience.gatherquality?yes) [No](https://command:python.datascience.gatherquality?no)

# %%
import os
from torchvision import datasets, models, transforms


# %%
from helper import *
path = os.path.join(os.getcwd(), 'images')
dataset_url = 'http://www.robots.ox.ac.uk/~vgg/data/pets/data/images.tar.gz'
dataset_path = fetch_and_untar(dataset_url, path)


# %%
dataloaders, dataset_sizes, class_names = transform_images_to_tensors(dataset_path)


# %%
device = use_gpu_if_avail()


# %%
model_ft = models.resnet18(pretrained=True)
setup_model(model_ft, device)


# %%
model_ft = train_model(model_ft, device, dataloaders, dataset_sizes, num_epochs=1)


# %%
save_best_model(model_ft)


